services:
  receipt-tracker:
    image: rotour/receipt-tracker:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - rotour/receipt-tracker:latest
    platform: linux/amd64

    ports:
      - "5173:3000"